name: Extract and Modify NDK Bridge Tar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sleuthkit p7zip-full git binwalk
        sudo apt-get install -y python3-pip
        sudo pip3 install binwalk

    - name: Clone Droid-NDK-Extractor repository
      uses: actions/checkout@v3
      with:
        repository: xiaoheiCat/Droid-NDK-Extractor_for_Redroid
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Make the extraction script executable
      run: |
        cd Droid-NDK-Extractor
        chmod +x android-extract-ndk.sh

    - name: Run the extraction script for x86_64 architecture
      run: |
        cd Droid-NDK-Extractor
        ./android-extract-ndk.sh x86_64

    - name: Create working directory and extract the generated tar
      run: |
        mkdir -p Droid-NDK-Extractor/working/extracted/native-bridge
        cd Droid-NDK-Extractor/working/extracted/native-bridge
        tar -xpf ../native-bridge.tar

    - name: Fix file and directory permissions
      run: |
        cd Droid-NDK-Extractor/working/extracted/native-bridge
        chmod 0644 system/etc/init/ndk_translation_arm64.rc
        chmod 0755 system/bin/arm
        chmod 0755 system/bin/arm64
        chmod 0755 system/lib/arm
        chmod 0755 system/lib64/arm64
        chmod 0644 system/etc/binfmt_misc/*

    - name: Repack the tar file with fixed permissions
      run: |
        cd Droid-NDK-Extractor/working/extracted/native-bridge
        tar -cpf ../native-bridge-fixed.tar system

    - name: Clean up temporary directory
      run: |
        rm -rf Droid-NDK-Extractor/working/extracted/native-bridge

    - name: Upload the modified tar file as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: native-bridge-fixed.tar
        path: Droid-NDK-Extractor/working/extracted/native-bridge-fixed.tar
